FROM ebit.tpb.vn/rhel8-nginx118:latest

USER 0

COPY nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /var/www/sale-web-portal/*

ADD sale-web-portal /var/www/sale-web-portal

RUN chown -R 1001:0 /var/www/sale-web-portal

USER 1001

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
