export enum NotificationConst {
  WAIT_SEND = 1,
  INACTIVE = 0,
  DRAFT = 3,
  SENT = 2,
  GROUP_VIEW_UNIT = 'UNIT',
  GROUP_VIEW_ROLE = 'ROLE',
  GROUP_VIEW_BRANCH = 'BRANCH',
  GROUP_VIEW_PERSON = 'PERSON',
}
