export enum NewsEnum {
  STATUS_DRAFT = 0,
  STATUS_PUBLISHED = 1,
  STATUS_PENDING_PUBLISH = 2,
  LEVEL_NORMAL = 'BINHTHUONG',
  LEVEL_IMPORTANT = 'QUANTRONG',
  LEVEL_VERY_IMPORTANT = 'RATQUANTRONG'
}
