export enum NewsEnum {
  STATUS_DRAFT = 0,
  STATUS_PUBLISHED = 1,
  STATUS_PENDING_PUBLISH = 2,
  LEVEL_NORMAL = 'BINHTHUONG',
  LEVEL_IMPORTANT = 'QUANTRONG',
  LEVEL_VERY_IMPORTANT = 'RATQUANTRONG',
  GROUP_VIEW_UNIT = 'UNIT',
  GROUP_VIEW_ROLE = 'ROLE',
  GROUP_VIEW_BRANCH = 'BRANCH',
  STATUS_DELETED = 10
}
